### NEW NOTE - BAD
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Bad request",
    "id": "42"
}

### NEW NOTE - GOOD
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Lorem ipsum"
}

### ALL NOTES
GET http://localhost:3001/api/notes

### SINGLE NOTE
GET http://localhost:3001/api/notes/1

### SINGLE NOTE
GET http://localhost:3001/api/notes/0

